In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet

In [2]:
df=pd.read_csv('sl1.csv')
df.head()

   Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    5 non-null      int64
 1   Price   5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [4]:
# set target and features
target=df[['Price']]
features=df.drop(columns=['Price'])

In [5]:
# splitting
x_train,x_test,y_train,y_test=train_test_split(target,features,train_size=0.7,random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3, 1)
(2, 1)
(3, 1)
(2, 1)

In [6]:
# which model used
lin=LinearRegression()
lin.fit(x_train,y_train)

LinearRegression()

In [7]:
# training validation
y_pred=lin.predict(x_train)
r2_score(y_train,y_pred)

0.9591026776589222

In [8]:
# testing validation
y_pred1=lin.predict(x_test)
r2_score(y_test,y_pred1)

0.9015044235984887

In [9]:
lasso=Lasso(alpha=4)
lasso.fit(x_train,y_train)

Lasso(alpha=4)

In [10]:
# training validation 
y_pred=lasso.predict(x_train)
r2_score(y_train,y_pred)

0.9591026776589148

In [11]:
# testing validation
y_pred1=lasso.predict(x_test)
r2_score(y_test,y_pred1)

0.9015045156432061

In [12]:
params=dict(alpha=range(1,5))
params

{'alpha': range(1, 5)}

In [13]:
grid_search=GridSearchCV(lasso,params)
grid_search.fit(x_train,y_train)
grid_search.best_params_

ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=3.

# 2) KNN

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
target=df['species']
features=df.drop(columns=['species'])

In [4]:
x_train,x_test,y_train,y_test=train_test_split(target,features,train_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(30,)
(120,)
(30, 4)
(120, 4)

In [ ]:
knn=KNeighborsClassifier(